apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-access
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubectl-access-binding
subjects:
- kind: ServiceAccount
  name: kubectl-access
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
